[invalid.py]
  [test_params_contexts_invalid_value[value1\]]
    expected: FAIL
